#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path" --depth 1 --single-branch --branch=main --filter=blob:none
	fi
}

clone_repo chromium chromium
clone_repo Alex313031 thorium

known_failures="$(cat script/known_failures.txt)"

# shellcheck disable=2046
tree-sitter parse -q \
	'examples/**/*.gn' \
	'examples/**/*.gni' \
	$(for file in $known_failures; do echo "!${file}"; done)

example_count=$(find examples -name '*.gn' -o -name '*.gni' | wc -l)
failure_count=$(wc -w <<<"$known_failures")
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	"$success_count" "$example_count" "$success_percent"
